# Generated by Django 4.2.7 on 2026-02-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("behavior", "0001_initial_behavior_tables"),
        ("teaching_sessions", "0001_initial"),
        ("groups", "0003_alter_groupannouncement_publish_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("grades", "0003_alter_grade_grade_date"),
        ("students", "0004_alter_student_email_alter_student_phone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentPoints",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_points", models.IntegerField(default=0)),
                ("total_earned", models.PositiveIntegerField(default=0)),
                ("total_deducted", models.PositiveIntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_balances",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_point_balances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_points",
                "indexes": [
                    models.Index(
                        fields=["teacher", "total_points"],
                        name="student_poi_teacher_b6bfef_idx",
                    ),
                    models.Index(
                        fields=["student"], name="student_poi_student_e29940_idx"
                    ),
                ],
                "unique_together": {("student", "teacher")},
            },
        ),
        migrations.CreateModel(
            name="Prize",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("points_required", models.PositiveIntegerField()),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(default="#FFD700", max_length=7)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prizes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "prizes",
                "ordering": ["points_required"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "is_active", "points_required"],
                        name="prizes_teacher_d036c4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PointTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.IntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("attendance", "حضور"),
                            ("grade", "درجة امتحان"),
                            ("homework", "واجب"),
                            ("dictation", "إملاء"),
                            ("absence", "غياب"),
                            ("late", "تأخير"),
                            ("bad_behavior", "سلوك سيئ"),
                            ("manual", "يدوي"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "behavior_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="behavior.behaviorrecord",
                    ),
                ),
                (
                    "grade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="grades.grade",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_transactions",
                        to="teaching_sessions.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_transactions",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issued_point_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "point_transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "event_type", "date"],
                        name="point_trans_student_161288_idx",
                    ),
                    models.Index(
                        fields=["teacher", "date"],
                        name="point_trans_teacher_997f2c_idx",
                    ),
                    models.Index(
                        fields=["session"], name="point_trans_session_92c240_idx"
                    ),
                    models.Index(
                        fields=["grade"], name="point_trans_grade_i_f28818_idx"
                    ),
                    models.Index(
                        fields=["behavior_record"],
                        name="point_trans_behavio_6496e1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PointRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("attendance", "حضور"),
                            ("grade", "درجة امتحان"),
                            ("homework", "واجب"),
                            ("dictation", "إملاء"),
                            ("absence", "غياب"),
                            ("late", "تأخير"),
                            ("bad_behavior", "سلوك سيئ"),
                            ("manual", "يدوي"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points", models.IntegerField(help_text="موجب للمكافأة، سالب للخصم")),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="اتركه فارغًا ليطبق على جميع المجموعات",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="point_rules",
                        to="groups.group",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="point_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "point_rules",
                "ordering": ["event_type"],
                "indexes": [
                    models.Index(
                        fields=["teacher", "is_active"],
                        name="point_rules_teacher_3180f8_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="point_rules_event_t_746abd_idx"
                    ),
                ],
                "unique_together": {("teacher", "event_type", "group")},
            },
        ),
    ]
