# Generated by Django 4.2.7 on 2026-02-14 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('financial', 'Financial Optimization'), ('scheduling', 'Schedule Optimization'), ('engagement', 'Student Engagement'), ('retention', 'Student Retention'), ('growth', 'Business Growth'), ('efficiency', 'Operational Efficiency')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('implementation_steps', models.JSONField(default=list)),
                ('expected_impact', models.TextField(blank=True, null=True)),
                ('effort_level', models.CharField(choices=[('low', 'Low Effort'), ('medium', 'Medium Effort'), ('high', 'High Effort')], default='medium', max_length=20)),
                ('analysis_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_implemented', models.BooleanField(default=False)),
                ('implementation_date', models.DateTimeField(blank=True, null=True)),
                ('implementation_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'category', 'is_active'], name='suggestions_teacher_c0433a_idx'), models.Index(fields=['priority', 'is_active'], name='suggestions_priorit_47db8c_idx'), models.Index(fields=['created_at'], name='suggestions_created_c428a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('attendance', 'Attendance'), ('performance', 'Performance'), ('engagement', 'Engagement'), ('operational', 'Operational'), ('growth', 'Growth')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('insight_data', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'category', 'is_active'], name='insights_teacher_3c146d_idx'), models.Index(fields=['priority', 'is_active'], name='insights_priorit_377c7c_idx'), models.Index(fields=['created_at'], name='insights_created_87d375_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('widget_type', models.CharField(choices=[('chart', 'Chart'), ('metric', 'Metric'), ('list', 'List'), ('calendar', 'Calendar'), ('progress', 'Progress'), ('alert', 'Alert')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('data_source', models.CharField(max_length=50)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_widgets',
                'ordering': ['position_y', 'position_x'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='dashboard_w_teacher_480485_idx'), models.Index(fields=['widget_type'], name='dashboard_w_widget__47e2e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('snapshot_date', models.DateField()),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('new_students', models.PositiveIntegerField(default=0)),
                ('churned_students', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overdue_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punctuality_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_grade', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade_improvement', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notification_open_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('parent_engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('metrics_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['teacher', 'snapshot_type', 'snapshot_date'], name='analytics_s_teacher_c45f4c_idx'), models.Index(fields=['snapshot_date'], name='analytics_s_snapsho_4cbe40_idx')],
                'unique_together': {('teacher', 'snapshot_type', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_attendance', 'Low Attendance'), ('payment_overdue', 'Payment Overdue'), ('session_cancelled', 'Session Cancelled'), ('student_inactive', 'Student Inactive'), ('grade_drop', 'Grade Drop'), ('capacity_full', 'Capacity Full'), ('system_error', 'System Error'), ('data_sync', 'Data Sync Issue')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='warning', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('target_type', models.CharField(blank=True, max_length=20, null=True)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=200, null=True)),
                ('trigger_data', models.JSONField(default=dict)),
                ('suggested_actions', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'alert_type', 'is_active'], name='alerts_teacher_ba84a6_idx'), models.Index(fields=['severity', 'is_active'], name='alerts_severit_d2a5bb_idx'), models.Index(fields=['target_type', 'target_id'], name='alerts_target__4601ae_idx'), models.Index(fields=['created_at'], name='alerts_created_965da5_idx')],
            },
        ),
    ]
