# Generated by Django 4.2.7 on 2026-02-15 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_groupannouncement_publish_at'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='group',
            field=models.ForeignKey(blank=True, help_text='المجموعة المرتبطة بهذه الدفعة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='groups.group'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['group', 'status'], name='payments_group_i_be3efa_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'group'], name='payments_student_34ba31_idx'),
        ),
    ]
