# Generated by Django 4.2.7 on 2026-02-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_payment_group_payment_payments_group_i_be3efa_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of sessions this payment purchases"
            ),
        ),
    ]
