# Generated by Django 4.2.7 on 2026-02-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('rule_type', models.CharField(choices=[('attendance', 'Attendance Rule'), ('payment', 'Payment Rule'), ('grade', 'Grade Rule'), ('session', 'Session Rule'), ('student', 'Student Rule'), ('system', 'System Rule')], max_length=20)),
                ('trigger_event', models.CharField(choices=[('attendance_marked', 'Attendance Marked'), ('payment_received', 'Payment Received'), ('payment_overdue', 'Payment Overdue'), ('grade_added', 'Grade Added'), ('session_completed', 'Session Completed'), ('student_registered', 'Student Registered'), ('daily_check', 'Daily Check'), ('weekly_check', 'Weekly Check'), ('monthly_check', 'Monthly Check')], max_length=30)),
                ('conditions', models.JSONField(default=dict)),
                ('actions', models.JSONField(default=list)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('last_executed', models.DateTimeField(blank=True, null=True)),
                ('execution_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rules',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RuleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('attendance', 'Attendance Rule'), ('payment', 'Payment Rule'), ('grade', 'Grade Rule'), ('session', 'Session Rule'), ('student', 'Student Rule'), ('system', 'System Rule')], max_length=20)),
                ('template_config', models.JSONField(default=dict)),
                ('default_conditions', models.JSONField(default=dict)),
                ('default_actions', models.JSONField(default=list)),
                ('customizable_fields', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'rule_templates',
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='rule_templa_categor_29402c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('execution_order', models.CharField(choices=[('priority', 'By Priority'), ('sequential', 'Sequential'), ('parallel', 'Parallel')], default='priority', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rule_sets',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['teacher', 'is_active'], name='rule_sets_teacher_468959_idx')],
            },
        ),
        migrations.CreateModel(
            name='RuleExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(max_length=30)),
                ('trigger_data', models.JSONField(default=dict)),
                ('conditions_met', models.BooleanField()),
                ('actions_executed', models.JSONField(default=list)),
                ('execution_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('execution_time', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='rules_engine.rule')),
            ],
            options={
                'db_table': 'rule_executions',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['rule', 'executed_at'], name='rule_execut_rule_id_3b013c_idx'), models.Index(fields=['trigger_event', 'executed_at'], name='rule_execut_trigger_7c06f4_idx'), models.Index(fields=['execution_status'], name='rule_execut_executi_13534d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['teacher', 'rule_type', 'is_active'], name='rules_teacher_2b3af9_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['trigger_event', 'is_active'], name='rules_trigger_a68dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='rule',
            index=models.Index(fields=['priority'], name='rules_priorit_5b952b_idx'),
        ),
    ]
