# Generated by Django 4.2.7 on 2026-02-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='trigger_event',
            field=models.CharField(choices=[('student_absent', 'Student Absent'), ('student_late', 'Student Late'), ('payment_created', 'Payment Created'), ('payment_overdue', 'Payment Overdue'), ('payment_completed', 'Payment Completed'), ('grade_recorded', 'Grade Recorded'), ('low_grade', 'Low Grade'), ('excellent_grade', 'Excellent Grade'), ('session_created', 'Session Created'), ('daily_check', 'Daily Check'), ('weekly_check', 'Weekly Check'), ('monthly_check', 'Monthly Check')], max_length=30),
        ),
    ]
