# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('monthly', 'Monthly Subscription'), ('per_session', 'Per Session'), ('free', 'Free Student')], default='monthly', max_length=20)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('per_session_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('student_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('remaining_sessions', models.PositiveIntegerField(default=0)),
                ('total_sessions_bought', models.PositiveIntegerField(default=0)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentParentLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('can_receive_notifications', models.BooleanField(default=True)),
                ('can_view_grades', models.BooleanField(default=True)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_view_payments', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'db_table': 'student_parent_links',
                'indexes': [models.Index(fields=['student', 'is_active'], name='student_par_student_9dca9f_idx'), models.Index(fields=['parent', 'is_active'], name='student_par_parent__888074_idx'), models.Index(fields=['is_primary_contact'], name='student_par_is_prim_37cb1c_idx')],
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_monthly_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('custom_session_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='groups.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='students.student')),
            ],
            options={
                'db_table': 'student_groups',
                'indexes': [models.Index(fields=['student', 'is_active'], name='student_gro_student_9b7e25_idx'), models.Index(fields=['group', 'is_active'], name='student_gro_group_i_60c5c2_idx'), models.Index(fields=['enrollment_date'], name='student_gro_enrollm_44354f_idx')],
                'unique_together': {('student', 'group')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['teacher', 'is_active'], name='students_teacher_de79c9_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['code'], name='students_code_dfbc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['subscription_status'], name='students_subscri_abfe97_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_date'], name='students_registr_7721b6_idx'),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['teacher', 'is_active'], name='parents_teacher_183dc9_idx'),
        ),
    ]
