# Generated by Django 4.2.7 on 2026-02-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly Subscription"),
                    ("per_session", "Per Session"),
                    ("free", "Free Student"),
                ],
                default="per_session",
                max_length=20,
            ),
        ),
    ]
