# Generated by Django 4.2.7 on 2026-02-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_alter_student_subscription_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="discount_type",
            field=models.CharField(
                choices=[("percentage", "Percentage"), ("fixed", "Fixed Amount")],
                default="percentage",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
