# Generated by Django 4.2.7 on 2026-02-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0003_add_discount_type_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
