# Generated by Django 4.2.7 on 2026-02-14 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=10)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('data', models.JSONField(default=dict)),
                ('synced', models.BooleanField(default=False)),
                ('sync_attempts', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_queue',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('conflict', 'Conflict')], max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('sync_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sync.syncqueue')),
            ],
            options={
                'db_table': 'sync_logs',
                'ordering': ['-synced_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('local_data', models.JSONField(default=dict)),
                ('server_data', models.JSONField(default=dict)),
                ('resolution', models.CharField(choices=[('last_write_wins', 'Last Write Wins'), ('manual', 'Manual Resolution'), ('server_wins', 'Server Wins'), ('client_wins', 'Client Wins')], default='last_write_wins', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='sync.syncqueue')),
            ],
            options={
                'db_table': 'sync_conflicts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['user', 'synced'], name='sync_queue_user_id_ac3ac3_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['model_name', 'object_id'], name='sync_queue_model_n_d0c67a_idx'),
        ),
    ]
