# Generated by Django 4.2.7 on 2026-02-14 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20)),
                ('actual_start_time', models.TimeField(blank=True, null=True)),
                ('actual_end_time', models.TimeField(blank=True, null=True)),
                ('repeat_type', models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='none', max_length=20)),
                ('repeat_until', models.DateField(blank=True, null=True)),
                ('repeat_count', models.PositiveIntegerField(blank=True, null=True)),
                ('lesson_content', models.TextField(blank=True, null=True)),
                ('homework_assigned', models.TextField(blank=True, null=True)),
                ('materials_used', models.TextField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='groups.group')),
                ('parent_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repeated_sessions', to='teaching_sessions.session')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SessionReminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('before_1h', '1 Hour Before'), ('before_30m', '30 Minutes Before'), ('before_15m', '15 Minutes Before'), ('at_start', 'At Session Start')], max_length=20)),
                ('reminder_time', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='teaching_sessions.session')),
            ],
            options={
                'db_table': 'session_reminders',
                'indexes': [models.Index(fields=['session', 'reminder_type'], name='session_rem_session_35d019_idx'), models.Index(fields=['reminder_time', 'is_sent'], name='session_rem_reminde_6aebda_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField()),
                ('note_type', models.CharField(choices=[('general', 'General Note'), ('student_behavior', 'Student Behavior'), ('lesson_progress', 'Lesson Progress'), ('homework', 'Homework'), ('reminder', 'Reminder')], default='general', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='teaching_sessions.session')),
            ],
            options={
                'db_table': 'session_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'note_type'], name='session_not_session_ce0c91_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='session_materials/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('usage_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_materials', to='teaching_sessions.session')),
            ],
            options={
                'db_table': 'session_materials',
                'indexes': [models.Index(fields=['session'], name='session_mat_session_4c5fe3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['group', 'date', 'is_active'], name='sessions_group_i_778909_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'start_time'], name='sessions_date_40ff50_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['repeat_type'], name='sessions_repeat__75cb6b_idx'),
        ),
    ]
