# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('receipt_type', models.CharField(choices=[('payment', 'Payment Receipt'), ('monthly', 'Monthly Receipt'), ('refund', 'Refund Receipt'), ('adjustment', 'Adjustment Receipt')], default='payment', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Generation'), ('generated', 'Generated'), ('sent', 'Sent'), ('failed', 'Generation Failed')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('sent_via_whatsapp', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_receipts', models.PositiveIntegerField(default=0)),
                ('processed_receipts', models.PositiveIntegerField(default=0)),
                ('failed_receipts', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipt_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('payment', 'Payment Receipt'), ('monthly', 'Monthly Receipt'), ('refund', 'Refund Receipt')], max_length=20)),
                ('header_text', models.CharField(blank=True, max_length=200, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='receipt_logos/')),
                ('include_student_details', models.BooleanField(default=True)),
                ('include_payment_breakdown', models.BooleanField(default=True)),
                ('include_signature', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#000000', max_length=7)),
                ('secondary_color', models.CharField(default='#666666', max_length=7)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipt_templates',
                'indexes': [models.Index(fields=['teacher', 'template_type', 'is_active'], name='receipt_tem_teacher_aab41c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('generated', 'PDF Generated'), ('sent_email', 'Sent via Email'), ('sent_whatsapp', 'Sent via WhatsApp'), ('failed', 'Generation Failed'), ('retry', 'Retry Attempted')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('success', models.BooleanField()),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='receipts.receipt')),
            ],
            options={
                'db_table': 'receipt_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['receipt', 'action'], name='receipt_log_receipt_04e7b4_idx'), models.Index(fields=['created_at'], name='receipt_log_created_6ea302_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='receipts.receipt')),
            ],
            options={
                'db_table': 'receipt_items',
                'indexes': [models.Index(fields=['receipt'], name='receipt_ite_receipt_7a351d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReceiptBatchItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_items', to='receipts.receiptbatch')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt')),
            ],
            options={
                'db_table': 'receipt_batch_items',
                'indexes': [models.Index(fields=['batch', 'status'], name='receipt_bat_batch_i_915755_idx')],
                'unique_together': {('batch', 'receipt')},
            },
        ),
        migrations.AddIndex(
            model_name='receiptbatch',
            index=models.Index(fields=['teacher', 'status'], name='receipt_bat_teacher_7fe10c_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptbatch',
            index=models.Index(fields=['created_at'], name='receipt_bat_created_6ed178_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['receipt_number'], name='receipts_receipt_0f1a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['payment', 'status'], name='receipts_payment_a537b0_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['status', 'created_at'], name='receipts_status_3c94c2_idx'),
        ),
    ]
