# Generated by Django 4.2.7 on 2026-02-23 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0003_add_discount_type_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("teaching_sessions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BehaviorCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(default="#4A90D9", max_length=7)),
                ("notify_on_negative", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_categories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behavior_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BehaviorSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "summary_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly")],
                        max_length=10,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_records", models.PositiveIntegerField(default=0)),
                (
                    "average_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=4),
                ),
                ("excellent_count", models.PositiveIntegerField(default=0)),
                ("good_count", models.PositiveIntegerField(default=0)),
                ("satisfactory_count", models.PositiveIntegerField(default=0)),
                ("needs_improvement_count", models.PositiveIntegerField(default=0)),
                ("poor_count", models.PositiveIntegerField(default=0)),
                ("category_scores", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_summaries",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "db_table": "behavior_summaries",
                "ordering": ["-period_start"],
                "indexes": [
                    models.Index(
                        fields=["student", "summary_type", "period_start"],
                        name="behavior_su_student_198093_idx",
                    )
                ],
                "unique_together": {("student", "summary_type", "period_start")},
            },
        ),
        migrations.CreateModel(
            name="BehaviorRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("excellent", "ممتاز"),
                            ("good", "جيد"),
                            ("satisfactory", "مقبول"),
                            ("needs_improvement", "يحتاج تحسين"),
                            ("poor", "ضعيف"),
                        ],
                        max_length=20,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=3)),
                ("notes", models.TextField(blank=True, null=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("parent_notified", models.BooleanField(default=False)),
                ("notified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="behavior.behaviorcategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_behavior_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="behavior_records",
                        to="teaching_sessions.session",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_records",
                        to="students.student",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="behavior_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "behavior_records",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "date"],
                        name="behavior_re_student_712c24_idx",
                    ),
                    models.Index(
                        fields=["student", "rating"],
                        name="behavior_re_student_6cff78_idx",
                    ),
                    models.Index(
                        fields=["teacher", "date"],
                        name="behavior_re_teacher_4aae3a_idx",
                    ),
                    models.Index(
                        fields=["category", "date"],
                        name="behavior_re_categor_70b7f4_idx",
                    ),
                    models.Index(
                        fields=["session"], name="behavior_re_session_387b41_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="behaviorcategory",
            index=models.Index(
                fields=["teacher", "is_active"], name="behavior_ca_teacher_398419_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="behaviorcategory",
            unique_together={("teacher", "name")},
        ),
    ]
