# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('letter_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grades',
                'ordering': ['-grade_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('min_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_types', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradeSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('monthly', 'Monthly'), ('term', 'Term'), ('semester', 'Semester'), ('yearly', 'Yearly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_grades', models.PositiveIntegerField(default=0)),
                ('average_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('average_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('overall_letter_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('grade_type_averages', models.JSONField(default=dict)),
                ('class_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('total_students', models.PositiveIntegerField(blank=True, null=True)),
                ('improvement_trend', models.CharField(blank=True, choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_summaries', to='students.student')),
            ],
            options={
                'db_table': 'grade_summaries',
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('scale_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'grade_scales',
            },
        ),
        migrations.CreateModel(
            name='GradeComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='grades.grade')),
            ],
            options={
                'db_table': 'grade_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_grade', 'Low Grade'), ('failing_grade', 'Failing Grade'), ('grade_drop', 'Grade Drop'), ('missing_grades', 'Missing Grades'), ('improvement', 'Grade Improvement')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('trigger_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='grades.grade')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_grade_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_alerts', to='students.student')),
            ],
            options={
                'db_table': 'grade_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.gradetype'),
        ),
        migrations.AddField(
            model_name='grade',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='sessions.session'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='gradetype',
            index=models.Index(fields=['teacher', 'is_active'], name='grade_types_teacher_0e7b47_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradetype',
            unique_together={('teacher', 'name')},
        ),
        migrations.AddIndex(
            model_name='gradesummary',
            index=models.Index(fields=['student', 'summary_type'], name='grade_summa_student_1f3ad9_idx'),
        ),
        migrations.AddIndex(
            model_name='gradesummary',
            index=models.Index(fields=['period_start', 'period_end'], name='grade_summa_period__7530d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gradesummary',
            unique_together={('student', 'summary_type', 'period_start', 'period_end')},
        ),
        migrations.AddIndex(
            model_name='gradescale',
            index=models.Index(fields=['teacher', 'is_active'], name='grade_scale_teacher_37218e_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecomment',
            index=models.Index(fields=['grade', 'is_private'], name='grade_comme_grade_i_2f8037_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecomment',
            index=models.Index(fields=['created_at'], name='grade_comme_created_f37de1_idx'),
        ),
        migrations.AddIndex(
            model_name='gradealert',
            index=models.Index(fields=['student', 'alert_type', 'is_active'], name='grade_alert_student_70489c_idx'),
        ),
        migrations.AddIndex(
            model_name='gradealert',
            index=models.Index(fields=['severity', 'is_active'], name='grade_alert_severit_d021e4_idx'),
        ),
        migrations.AddIndex(
            model_name='gradealert',
            index=models.Index(fields=['created_at'], name='grade_alert_created_9bffb3_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'grade_type', 'is_active'], name='grades_student_d11447_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['grade_date', 'is_active'], name='grades_grade_d_23d9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['session', 'is_active'], name='grades_session_6751f1_idx'),
        ),
    ]
