# Generated by Django 4.2.7 on 2026-02-14 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_grade_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
