# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNotificationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_received_email', models.BooleanField(default=True)),
                ('payment_received_whatsapp', models.BooleanField(default=True)),
                ('payment_overdue_email', models.BooleanField(default=True)),
                ('payment_overdue_whatsapp', models.BooleanField(default=True)),
                ('session_reminder_email', models.BooleanField(default=True)),
                ('session_reminder_whatsapp', models.BooleanField(default=True)),
                ('session_cancelled_email', models.BooleanField(default=True)),
                ('session_cancelled_whatsapp', models.BooleanField(default=True)),
                ('new_student_email', models.BooleanField(default=True)),
                ('student_absence_email', models.BooleanField(default=True)),
                ('student_absence_whatsapp', models.BooleanField(default=True)),
                ('smart_alerts_email', models.BooleanField(default=True)),
                ('smart_alerts_whatsapp', models.BooleanField(default=True)),
                ('system_updates_email', models.BooleanField(default=True)),
                ('backup_completion_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='TeacherStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('stat_type', models.CharField(choices=[('daily', 'Daily'), ('monthly', 'Monthly')], max_length=20)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('active_students', models.PositiveIntegerField(default=0)),
                ('new_students', models.PositiveIntegerField(default=0)),
                ('total_groups', models.PositiveIntegerField(default=0)),
                ('active_groups', models.PositiveIntegerField(default=0)),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('cancelled_sessions', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pending_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('overdue_payments', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_stats',
                'indexes': [models.Index(fields=['teacher', 'date', 'stat_type'], name='teacher_sta_teacher_e82920_idx'), models.Index(fields=['date', 'stat_type'], name='teacher_sta_date_281455_idx')],
                'unique_together': {('teacher', 'date', 'stat_type')},
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_name', models.CharField(max_length=200)),
                ('center_address', models.TextField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subscription_plan', models.CharField(choices=[('free', 'Free Plan'), ('basic', 'Basic Plan'), ('premium', 'Premium Plan'), ('enterprise', 'Enterprise Plan')], default='free', max_length=50)),
                ('max_students', models.PositiveIntegerField(default=50)),
                ('max_groups', models.PositiveIntegerField(default=20)),
                ('default_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=5)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('default_session_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('default_monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('whatsapp_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('smart_insights_enabled', models.BooleanField(default=True)),
                ('auto_alerts_enabled', models.BooleanField(default=True)),
                ('auto_receipts_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teacher_profiles',
                'indexes': [models.Index(fields=['subscription_plan'], name='teacher_pro_subscri_dcc80b_idx'), models.Index(fields=['created_at'], name='teacher_pro_created_a093ae_idx')],
            },
        ),
    ]
