# Generated by Django 4.2.7 on 2026-02-22 00:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teachers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="teacherprofile",
            name="trial_start_date",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2026, 2, 22, 0, 39, 54, 725251, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="teacherprofile",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("trial", "Trial Period"),
                    ("free", "Free Plan"),
                    ("basic", "Basic Plan"),
                    ("premium", "Premium Plan"),
                    ("enterprise", "Enterprise Plan"),
                ],
                default="trial",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["trial_end_date"], name="teacher_pro_trial_e_5a1d55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacherprofile",
            index=models.Index(
                fields=["subscription_end_date"], name="teacher_pro_subscri_adb0b2_idx"
            ),
        ),
    ]
