# Generated by Django 4.2.7 on 2026-02-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Plan duration in days (30=monthly, 365=yearly, 0=lifetime)",
            ),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="name_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
