# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('group_type', models.CharField(choices=[('center', 'Center Class'), ('premium_center', 'Premium Center Class'), ('private', 'Private Class'), ('private_lesson', 'Private Lesson'), ('online', 'Online Class')], default='center', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('grade_level', models.CharField(blank=True, max_length=50, null=True)),
                ('max_students', models.PositiveIntegerField(default=30)),
                ('current_students_count', models.PositiveIntegerField(default=0)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('session_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('group_discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sessions_per_month', models.PositiveIntegerField(default=8)),
                ('session_duration_minutes', models.PositiveIntegerField(default=60)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('online_meeting_link', models.URLField(blank=True, null=True)),
                ('meeting_password', models.CharField(blank=True, max_length=50, null=True)),
                ('schedule_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('effective_from', models.DateField()),
                ('effective_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='groups.group')),
            ],
            options={
                'db_table': 'group_schedules',
                'indexes': [models.Index(fields=['group', 'weekday', 'is_active'], name='group_sched_group_i_addbfd_idx'), models.Index(fields=['effective_from', 'effective_until'], name='group_sched_effecti_a1d7f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('document', 'Document'), ('presentation', 'Presentation'), ('video', 'Video'), ('audio', 'Audio'), ('link', 'External Link'), ('other', 'Other')], default='document', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='group_materials/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='groups.group')),
            ],
            options={
                'db_table': 'group_materials',
                'indexes': [models.Index(fields=['group', 'is_public'], name='group_mater_group_i_211388_idx'), models.Index(fields=['material_type'], name='group_mater_materia_4cffe7_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('send_notification', models.BooleanField(default=True)),
                ('publish_at', models.DateTimeField()),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='groups.group')),
            ],
            options={
                'db_table': 'group_announcements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'is_active'], name='group_annou_group_i_e4d4cb_idx'), models.Index(fields=['publish_at', 'expire_at'], name='group_annou_publish_559bcf_idx'), models.Index(fields=['is_urgent'], name='group_annou_is_urge_790c29_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['teacher', 'is_active'], name='groups_teacher_480060_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['group_type'], name='groups_group_t_30329f_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['subject', 'grade_level'], name='groups_subject_7a996d_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['created_at'], name='groups_created_d34ebd_idx'),
        ),
    ]
