# Generated by Django 4.2.7 on 2026-02-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupschedule',
            name='effective_from',
            field=models.DateField(blank=True, help_text='When this schedule becomes effective', null=True),
        ),
        migrations.AlterField(
            model_name='groupschedule',
            name='effective_until',
            field=models.DateField(blank=True, help_text='When this schedule expires', null=True),
        ),
    ]
