# Generated by Django 4.2.7 on 2026-02-15 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groupschedule_effective_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupannouncement',
            name='publish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
