# Generated by Django 4.2.7 on 2026-02-14 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DangerZoneAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('delete_students', 'Delete All Students'), ('delete_sessions', 'Delete All Sessions'), ('delete_payments', 'Delete All Payments'), ('delete_grades', 'Delete All Grades'), ('delete_all', 'Delete ALL Data')], max_length=30)),
                ('confirmation_text', models.CharField(max_length=200)),
                ('items_affected', models.IntegerField(default=0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danger_zone_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'danger_zone_actions',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('center_name', models.CharField(default='My Learning Center', max_length=200)),
                ('teacher_name', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=5)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('currency', models.CharField(default='SAR', max_length=3)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('attendance_alerts', models.BooleanField(default=True)),
                ('payment_alerts', models.BooleanField(default=True)),
                ('grade_alerts', models.BooleanField(default=True)),
                ('low_attendance_rate', models.IntegerField(default=70)),
                ('consecutive_absences', models.IntegerField(default=3)),
                ('overdue_payment_days', models.IntegerField(default=7)),
                ('low_grade_threshold', models.IntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'App Settings',
                'db_table': 'app_settings',
            },
        ),
    ]
