# Generated by Django 4.2.7 on 2026-02-15 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='auto_logout_enabled',
            field=models.BooleanField(default=True, help_text='Auto logout after timeout'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='default_session_duration',
            field=models.IntegerField(default=60, help_text='Default session duration in minutes'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='digest_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', help_text='Frequency of digest notifications', max_length=10),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='digest_notifications',
            field=models.BooleanField(default=False, help_text='Send digest instead of realtime'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notification_quiet_end',
            field=models.TimeField(blank=True, help_text='End of quiet hours', null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='notification_quiet_start',
            field=models.TimeField(blank=True, help_text='Start of quiet hours', null=True),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='require_pin_for_danger_zone',
            field=models.BooleanField(default=True, help_text='Require PIN for dangerous operations'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=60, help_text='Session timeout in minutes'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Enable two-factor authentication'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='weekend_days',
            field=models.CharField(default='FRI,SAT', help_text='Weekend days (comma-separated)', max_length=20),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='working_hours_end',
            field=models.TimeField(default='20:00', help_text='End of working hours'),
        ),
        migrations.AddField(
            model_name='appsettings',
            name='working_hours_start',
            field=models.TimeField(default='08:00', help_text='Start of working hours'),
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('pin_change', 'PIN Changed'), ('pin_change_failed', 'PIN Change Failed'), ('login_failed', 'Failed Login'), ('data_export', 'Data Exported'), ('settings_changed', 'Settings Changed'), ('danger_zone_action', 'Danger Zone Action'), ('two_factor_enabled', 'Two-Factor Enabled'), ('two_factor_disabled', 'Two-Factor Disabled')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', '-created_at'], name='security_lo_teacher_6112af_idx'), models.Index(fields=['event_type', '-created_at'], name='security_lo_event_t_e67194_idx')],
            },
        ),
    ]
