# Generated by Django 4.2.7 on 2026-02-14 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher'), ('group', 'Group'), ('all_students', 'All Students')], max_length=20)),
                ('recipient_id', models.UUIDField(blank=True, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=200, null=True)),
                ('recipient_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('payment', 'Payment'), ('session', 'Session'), ('attendance', 'Attendance'), ('grade', 'Grade'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('receipt', 'Receipt'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('sms', 'SMS')], default='whatsapp', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('notification_type', models.CharField(choices=[('payment', 'Payment'), ('session', 'Session'), ('attendance', 'Attendance'), ('grade', 'Grade'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('alert', 'Alert'), ('receipt', 'Receipt'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('push', 'Push Notification'), ('sms', 'SMS')], max_length=20)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('available_variables', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_templates',
                'indexes': [models.Index(fields=['teacher', 'notification_type', 'channel'], name='notificatio_teacher_97f99a_idx')],
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Created'), ('sent', 'Sent'), ('failed', 'Failed'), ('retried', 'Retried'), ('cancelled', 'Cancelled'), ('whatsapp_sent', 'WhatsApp Sent'), ('email_sent', 'Email Sent'), ('push_sent', 'Push Sent'), ('sms_sent', 'SMS Sent')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
                ('payload', models.JSONField(default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notification', 'action'], name='notificatio_notific_96fad3_idx'), models.Index(fields=['created_at'], name='notificatio_created_45a1e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_notifications', models.PositiveIntegerField(default=0)),
                ('sent_notifications', models.PositiveIntegerField(default=0)),
                ('failed_notifications', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_batches',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['teacher', 'status'], name='notificatio_teacher_bc2de7_idx'), models.Index(fields=['created_at'], name='notificatio_created_9e187f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['teacher', 'status'], name='notificatio_teacher_020bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_id'], name='notificatio_recipie_3fe303_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at', 'status'], name='notificatio_schedul_c045c8_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'channel'], name='notificatio_notific_1897f3_idx'),
        ),
    ]
