# Generated by Django 4.2.7 on 2026-02-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_sessions', models.PositiveIntegerField(default=0)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
                ('late_count', models.PositiveIntegerField(default=0)),
                ('excused_count', models.PositiveIntegerField(default=0)),
                ('attendance_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('punctuality_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student')),
            ],
            options={
                'db_table': 'attendance_summaries',
                'indexes': [models.Index(fields=['student', 'summary_type'], name='attendance__student_60bbed_idx'), models.Index(fields=['period_start', 'period_end'], name='attendance__period__02b1b6_idx')],
                'unique_together': {('student', 'summary_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceQRCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.CharField(max_length=255, unique=True)),
                ('qr_data', models.TextField()),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('max_scans', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_qr_codes', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='sessions.session')),
            ],
            options={
                'db_table': 'attendance_qr_codes',
                'indexes': [models.Index(fields=['qr_token'], name='attendance__qr_toke_6752fa_idx'), models.Index(fields=['session', 'is_active'], name='attendance__session_5e194d_idx'), models.Index(fields=['valid_from', 'valid_until'], name='attendance__valid_f_2ec444_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('consecutive_absence', 'Consecutive Absences'), ('low_attendance', 'Low Attendance Rate'), ('frequent_lateness', 'Frequent Lateness'), ('no_attendance_marked', 'No Attendance Marked')], max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('trigger_data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_attendance_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_alerts', to='students.student')),
            ],
            options={
                'db_table': 'attendance_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'alert_type', 'is_active'], name='attendance__student_468239_idx'), models.Index(fields=['severity', 'is_active'], name='attendance__severit_53bf18_idx'), models.Index(fields=['created_at'], name='attendance__created_9f96d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence')], default='present', max_length=20)),
                ('method', models.CharField(choices=[('manual', 'Manual Entry'), ('qr_code', 'QR Code Scan'), ('bulk', 'Bulk Entry'), ('auto', 'Automatic')], default='manual', max_length=20)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('excuse_reason', models.TextField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='sessions.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student')),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['session', 'status'], name='attendance_session_0dca61_idx'), models.Index(fields=['student', 'status'], name='attendance_student_bc7a65_idx'), models.Index(fields=['marked_at'], name='attendance_marked__ce655c_idx'), models.Index(fields=['qr_token'], name='attendance_qr_toke_350119_idx')],
                'unique_together': {('session', 'student')},
            },
        ),
    ]
