# Generated by Django 4.2.7 on 2026-02-14 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teaching_sessions', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='teaching_sessions.session'),
        ),
        migrations.AlterField(
            model_name='attendanceqrcode',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='teaching_sessions.session'),
        ),
    ]
